# For detailed information on configuring the parameter_bridge, please refer to:
# https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge#example-5-configuring-the-bridge-via-yaml

- topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "ignition.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "battery"
  gz_topic_name: "model/panther/battery/panther_battery/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "ignition.msgs.BatteryState"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS

# Topic for Twist data from Ignition teleopt widget
- topic_name: "cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: GZ_TO_ROS

- ros_topic_name: "velodyne/scan"
  gz_topic_name: "velodyne_points"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS

- ros_topic_name: "rplidar/scan"
  gz_topic_name: "scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "ignition.msgs.LaserScan"
  subscriber_queue: 10
  publisher_queue: 10
  direction: GZ_TO_ROS

- ros_topic_name: "gps/fix"
  gz_topic_name: "world/dome_world/model/panther/link/gps_link/sensor/navsat/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "ignition.msgs.NavSat"
  direction: GZ_TO_ROS